/********************************************************************
* SRSCommonDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SRSCommonDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSRSCommonDict();
extern void G__cpp_setup_inheritanceSRSCommonDict();
extern void G__cpp_setup_typetableSRSCommonDict();
extern void G__cpp_setup_memvarSRSCommonDict();
extern void G__cpp_setup_globalSRSCommonDict();
extern void G__cpp_setup_memfuncSRSCommonDict();
extern void G__cpp_setup_funcSRSCommonDict();
extern void G__set_cpp_environmentSRSCommonDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Common.h"
#include "SRSCommon.h"
#include "SRSMapping.h"
#include "SRSConfiguration.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SRSCommonDictLN_TClass;
extern G__linked_taginfo G__SRSCommonDictLN_TBuffer;
extern G__linked_taginfo G__SRSCommonDictLN_TMemberInspector;
extern G__linked_taginfo G__SRSCommonDictLN_TObject;
extern G__linked_taginfo G__SRSCommonDictLN_TString;
extern G__linked_taginfo G__SRSCommonDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_amore;
extern G__linked_taginfo G__SRSCommonDictLN_amorecLcLSRS;
extern G__linked_taginfo G__SRSCommonDictLN_amorecLcLSRScLcLcommon;
extern G__linked_taginfo G__SRSCommonDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_amorecLcLSRScLcLcommoncLcLSRSCommon;
extern G__linked_taginfo G__SRSCommonDictLN_listlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_SRSMapping;
extern G__linked_taginfo G__SRSCommonDictLN_maplEintcOTStringcOlesslEintgRcOallocatorlEpairlEconstsPintcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOlistlEintcOallocatorlEintgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOlistlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_listlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOintcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOfloatcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplEintcOlistlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOlistlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_maplETStringcOlistlETStringcOallocatorlETStringgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOlistlETStringcOallocatorlETStringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSCommonDictLN_SRSConfiguration;

/* STUB derived class for protected member access */
