/********************************************************************
* SRSUIDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SRSUIDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSRSUIDict();
extern void G__cpp_setup_inheritanceSRSUIDict();
extern void G__cpp_setup_typetableSRSUIDict();
extern void G__cpp_setup_memvarSRSUIDict();
extern void G__cpp_setup_globalSRSUIDict();
extern void G__cpp_setup_memfuncSRSUIDict();
extern void G__cpp_setup_funcSRSUIDict();
extern void G__set_cpp_environmentSRSUIDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SRSUI.h"
#include "SRSUI2.h"
#include "SRSUI3.h"
#include "SRSUI.h"
#include "SRSUI2.h"
#include "SRSUI3.h"
#include "SRSUI4.h"
#include "SRSUI5.h"
#include "SRSUI6.h"
#include "SRSUI7.h"
#include "SRSUI8.h"
#include "SRSUI9.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SRSUIDictLN_TClass;
extern G__linked_taginfo G__SRSUIDictLN_TBuffer;
extern G__linked_taginfo G__SRSUIDictLN_TMemberInspector;
extern G__linked_taginfo G__SRSUIDictLN_TString;
extern G__linked_taginfo G__SRSUIDictLN_TList;
extern G__linked_taginfo G__SRSUIDictLN_amore;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLcore;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLcorecLcLRuntimeModule;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLsubscriber;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLsubscribercLcLSubscriberModule;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLui;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLuicLcLVisualModule;
extern G__linked_taginfo G__SRSUIDictLN_TQObjSender;
extern G__linked_taginfo G__SRSUIDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__SRSUIDictLN_TGTab;
extern G__linked_taginfo G__SRSUIDictLN_SRSMapping;
extern G__linked_taginfo G__SRSUIDictLN_maplETStringcOintcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRSUIDictLN_SRSConfiguration;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRS;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLcommon;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLcommoncLcLSRSCommon;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLui;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI;
extern G__linked_taginfo G__SRSUIDictLN_multimaplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI2;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI3;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI4;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI5;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI6;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI7;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI8;
extern G__linked_taginfo G__SRSUIDictLN_amorecLcLSRScLcLuicLcLSRSUI9;

/* STUB derived class for protected member access */
