/********************************************************************
* SRSPublisherDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SRSPublisherDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSRSPublisherDict();
extern void G__cpp_setup_inheritanceSRSPublisherDict();
extern void G__cpp_setup_typetableSRSPublisherDict();
extern void G__cpp_setup_memvarSRSPublisherDict();
extern void G__cpp_setup_globalSRSPublisherDict();
extern void G__cpp_setup_memfuncSRSPublisherDict();
extern void G__cpp_setup_funcSRSPublisherDict();
extern void G__set_cpp_environmentSRSPublisherDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SRSAPVEvent.h"
#include "SRSHit.h"
#include "SRSTrackFit.h"
#include "SRSCluster.h"
#include "SRSEventBuilder.h"
#include "SRSFECEventDecoder.h"
#include "SRSFECPedestalDecoder.h"
#include "SRSHistoManager.h"
#include "SRSPedestal.h"
#include "SRSRawPedestal.h"
#include "SRSPublisher.h"
#include "SRSTrack.h"
#include "SRSOutputROOT.h"
#include "SRSTrackBasedEfficiency.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SRSPublisherDictLN_TClass;
extern G__linked_taginfo G__SRSPublisherDictLN_TBuffer;
extern G__linked_taginfo G__SRSPublisherDictLN_TMemberInspector;
extern G__linked_taginfo G__SRSPublisherDictLN_TObject;
extern G__linked_taginfo G__SRSPublisherDictLN_TString;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_string;
extern G__linked_taginfo G__SRSPublisherDictLN_TList;
extern G__linked_taginfo G__SRSPublisherDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_TH1F;
extern G__linked_taginfo G__SRSPublisherDictLN_TH1S;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSHit;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSMapping;
extern G__linked_taginfo G__SRSPublisherDictLN_maplEintcOTStringcOlesslEintgRcOallocatorlEpairlEconstsPintcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOintcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOfloatcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSAPVEvent;
extern G__linked_taginfo G__SRSPublisherDictLN_multimaplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_listlESRSHitmUcOallocatorlESRSHitmUgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_TFile;
extern G__linked_taginfo G__SRSPublisherDictLN_TH2F;
extern G__linked_taginfo G__SRSPublisherDictLN_TTree;
extern G__linked_taginfo G__SRSPublisherDictLN_TNtuple;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSTrackFit;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSCluster;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSFECPedestalDecoder;
extern G__linked_taginfo G__SRSPublisherDictLN_maplEintcOvectorlEintcOallocatorlEintgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSRawPedestal;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSPedestal;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSEventBuilder;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOTListmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTListmUgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplEintcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSFECEventDecoder;
extern G__linked_taginfo G__SRSPublisherDictLN_eventHeaderStruct;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSConfiguration;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSTrack;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSTrackBasedEfficiency;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSHistoManager;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOTH1mUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTH1mUgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOvectorlETStringcOallocatorlETStringgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETStringcOallocatorlETStringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_maplETStringcOTObjectmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTObjectmUgRsPgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_vectorlETH2mUcOallocatorlETH2mUgRsPgR;
extern G__linked_taginfo G__SRSPublisherDictLN_amore;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLcore;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLpublisher;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLcorecLcLRuntimeModule;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLcorecLcLRun;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLcorecLcLAmoreEvent;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLcorecLcLSession;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLpublishercLcLPublisherModule;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLSRS;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLSRScLcLcommon;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLSRScLcLcommoncLcLSRSCommon;
extern G__linked_taginfo G__SRSPublisherDictLN_SRSOutputROOT;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLSRScLcLpublisher;
extern G__linked_taginfo G__SRSPublisherDictLN_amorecLcLSRScLcLpublishercLcLSRSPublisher;

/* STUB derived class for protected member access */
