/********************************************************************
* SRSSubscriberDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SRSSubscriberDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSRSSubscriberDict();
extern void G__cpp_setup_inheritanceSRSSubscriberDict();
extern void G__cpp_setup_typetableSRSSubscriberDict();
extern void G__cpp_setup_memvarSRSSubscriberDict();
extern void G__cpp_setup_globalSRSSubscriberDict();
extern void G__cpp_setup_memfuncSRSSubscriberDict();
extern void G__cpp_setup_funcSRSSubscriberDict();
extern void G__set_cpp_environmentSRSSubscriberDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SRSSubscriber.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SRSSubscriberDictLN_TClass;
extern G__linked_taginfo G__SRSSubscriberDictLN_TBuffer;
extern G__linked_taginfo G__SRSSubscriberDictLN_TMemberInspector;
extern G__linked_taginfo G__SRSSubscriberDictLN_amore;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLcore;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLsubscriber;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLcorecLcLRuntimeModule;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLsubscribercLcLSubscriberModule;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLSRS;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLSRScLcLcommon;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLSRScLcLcommoncLcLSRSCommon;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLSRScLcLsubscriber;
extern G__linked_taginfo G__SRSSubscriberDictLN_amorecLcLSRScLcLsubscribercLcLSRSSubscriber;

/* STUB derived class for protected member access */
